In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('Data/dataset.csv')

## Preguntas de Negocio

1. ¿Cuál es el precio promedio por categoría?
2. ¿Cuantas son las cantidades vendidas promedio por categoría?

In [17]:
df.groupby('category_id').aggregate({'price': 'mean', 'sold_quantity': 'mean' })

                    price  sold_quantity
category_id
MLA1000      5.957957e+03     397.617245
MLA1039      1.094025e+04     125.348000
MLA1051      3.033884e+04     195.058000
MLA1071      3.001024e+03     193.692000
MLA1132      1.963600e+03     230.015000
MLA1144      6.148511e+03     198.259000
MLA1168      1.724516e+03      15.433000
MLA1182      9.745474e+03     165.078000
MLA1246      1.984358e+03     389.005263
MLA1276      2.347666e+03     515.425000
MLA1367      1.762483e+03      48.802000
MLA1368      1.108608e+03     310.580000
MLA1384      1.943917e+03     369.795000
MLA1403      1.035699e+03     300.470470
MLA1430      2.134514e+03     386.030000
MLA1459      1.183796e+06       0.000000
MLA1499      4.356352e+03     420.828000
MLA1512      1.001968e+04     119.283456
MLA1540      1.068208e+04      20.442000
MLA1574      3.282782e+03     991.700000
MLA1648      4.096864e+04     399.973000
MLA1743      1.439518e+06       0.000000
MLA1953      1.209061e+03     137.987988
MLA2547      1.683967e+03       1.067067
MLA3025      1.468889e+03     108.537736
MLA3937      2.343986e+03     162.471000
MLA407134    4.252133e+03     390.041195
MLA409431    2.330398e+03     404.316000
MLA5725      3.267903e+03     369.784000
MLA5726      7.843648e+03     266.002000
MLA9304      8.463580e+02     195.818819